[project]
name = "ERP-System"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.6",
    "django-bolt>=0.9.1",
    "django-pandas>=0.6.7",
    "django-phonenumber-field[phonenumberslite]>=8.4.0",
    "django-redis[hiredis]>=7.0.0",
    "django-unfold>=0.97.0",
    "polars>=1.43.0",
    "psycopg[binary,pool]>=3.3.4",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = []
