# Generated by Django 6.0.6 on 2026-07-24 23:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Ledger'), ('SENT', 'Sent to Client'), ('PAID', 'Settled / Paid'), ('CANCELLED', 'Voided / Cancelled')], default='DRAFT', max_length=15)),
                ('is_locked', models.BooleanField(default=False)),
                ('eta_uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_invoices', to='crm.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.14'), max_digits=4)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='financials.invoice')),
            ],
        ),
    ]
